// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"
)

type Picture struct {
	ID          int32          `json:"id"`
	Description sql.NullString `json:"description"`
	UserID      sql.NullInt32  `json:"user_id"`
	Url         string         `json:"url"`
	Matches     int32          `json:"matches"`
	Rating      int32          `json:"rating"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Result struct {
	ID        int32         `json:"id"`
	PictureA  int32         `json:"picture_a"`
	PictureB  int32         `json:"picture_b"`
	Complete  bool          `json:"complete"`
	Winner    sql.NullInt32 `json:"winner"`
	CreatedAt time.Time     `json:"created_at"`
}

type User struct {
	ID           int32     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
